name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Check types
      run: npm run type:check
    - name: Check prettier
      run: npm run pretty:check
    - name: Build
      run: npm run build

